##目前已集成 mybatis-plus,druid,
##服务器配置
server:
  ##服务器的HTTP端口，默认为80
  port: 80
  servlet:
    ##应用的访问路径
    context-path: /
  tomcat:
    ##tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30

spring:
  profiles:
    active: druid