##mybatis-plus配置
mybatis-plus:
  ##Mapper.xml文件路径
  mapper-locations: classpath:mapper/*.xml
  ##MyBaits Bean文件路径（用逗号或分号分隔）
  type-aliases-package: com.guus.gjtest.bean
  ##配置项
  configuration:
    ##下划线转驼峰
    map-underscore-to-camel-case: true
    ##Oracle数据库必配
    jdbc-type-for-null: null
  global-config:
    ##是否控制台 print mybatis-plus 的 LOGO
    banner: true
    db-config:
      ##数据表下划线命名
      table-underline: true